# 100 numpy exercises

This is a collection of exercises that have been collected in the numpy mailing list, on stack overflow
and in the numpy documentation. The goal of this collection is to offer a quick reference for both old
and new users but also to provide a set of exercises for those who teach.


If you find an error or think you've a better way to solve some of them, feel
free to open an issue at <https://github.com/rougier/numpy-100>.

File automatically generated. See the documentation to update questions/answers/hints programmatically.

Run the `initialize.py` module, then for each question you can query the
answer or an hint with `hint(n)` or `answer(n)` for `n` question number.

In [192]:
from io import StringIO

from numpy import random as npr
from datetime import datetime
from scipy import spatial

#@formatter:off
%run initialise.py
#@formatter:on

np.set_printoptions(precision=4)

#### 1. Import the numpy package under the name `np` (★☆☆)

In [193]:
import numpy as np

#### 2. Print the numpy version and the configuration (★☆☆)

In [194]:
print(np.__version__)
np.show_config()

1.19.5
blas_mkl_info:
  NOT AVAILABLE
blis_info:
  NOT AVAILABLE
openblas_info:
    library_dirs = ['D:\\a\\1\\s\\numpy\\build\\openblas_info']
    libraries = ['openblas_info']
    language = f77
    define_macros = [('HAVE_CBLAS', None)]
blas_opt_info:
    library_dirs = ['D:\\a\\1\\s\\numpy\\build\\openblas_info']
    libraries = ['openblas_info']
    language = f77
    define_macros = [('HAVE_CBLAS', None)]
lapack_mkl_info:
  NOT AVAILABLE
openblas_lapack_info:
    library_dirs = ['D:\\a\\1\\s\\numpy\\build\\openblas_lapack_info']
    libraries = ['openblas_lapack_info']
    language = f77
    define_macros = [('HAVE_CBLAS', None)]
lapack_opt_info:
    library_dirs = ['D:\\a\\1\\s\\numpy\\build\\openblas_lapack_info']
    libraries = ['openblas_lapack_info']
    language = f77
    define_macros = [('HAVE_CBLAS', None)]


#### 3. Create a null vector of size 10 (★☆☆)

In [195]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

#### 4. How to find the memory size of any array (★☆☆)

In [196]:
arr = np.zeros((10, 10))
arr.size * arr.itemsize
#or
arr.nbytes

800

#### 5. How to get the documentation of the numpy add function from the command line? (★☆☆)

In [197]:
help(np.add)
#or
np.info(np.add)

Help on ufunc:

add = <ufunc 'add'>
    add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj])
    
    Add arguments element-wise.
    
    Parameters
    ----------
    x1, x2 : array_like
        The arrays to be added.
        If ``x1.shape != x2.shape``, they must be broadcastable to a common
        shape (which becomes the shape of the output).
    out : ndarray, None, or tuple of ndarray and None, optional
        A location into which the result is stored. If provided, it must have
        a shape that the inputs broadcast to. If not provided or None,
        a freshly-allocated array is returned. A tuple (possible only as a
        keyword argument) must have length equal to the number of outputs.
    where : array_like, optional
        This condition is broadcast over the input. At locations where the
        condition is True, the `out` array will be set to the ufunc result.
        Elsewhere, the `out` array wi

#### 6. Create a null vector of size 10 but the fifth value which is 1 (★☆☆)

In [198]:
arr = np.zeros(10)
arr[4] = 1
arr

array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0.])

#### 7. Create a vector with values ranging from 10 to 49 (★☆☆)

In [199]:
np.arange(10, 50)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

#### 8. Reverse a vector (first element becomes last) (★☆☆)

In [200]:
np.arange(10)[::-1]

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

#### 9. Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆)

In [201]:
np.arange(9).reshape((3, 3))

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

#### 10. Find indices of non-zero elements from [1,2,0,0,4,0] (★☆☆)

In [202]:
arr = np.array([1, 2, 0, 0, 4, 0])
np.arange(arr.size)[arr != 0]
# or
arr.nonzero()

(array([0, 1, 4], dtype=int64),)

#### 11. Create a 3x3 identity matrix (★☆☆)

In [203]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

#### 12. Create a 3x3x3 array with random values (★☆☆)

In [204]:
np.random.random((3, 3, 3))

array([[[0.0537, 0.9993, 0.1625],
        [0.5807, 0.9585, 0.5056],
        [0.7656, 0.2018, 0.2502]],

       [[0.9729, 0.5257, 0.7779],
        [0.1761, 0.4363, 0.1843],
        [0.2789, 0.6795, 0.4636]],

       [[0.9717, 0.7522, 0.9321],
        [0.3014, 0.3766, 0.8065],
        [0.7442, 0.1182, 0.64  ]]])

#### 13. Create a 10x10 array with random values and find the minimum and maximum values (★☆☆)

In [205]:
arr = np.random.random((10))
arr.min(), arr.max()

(0.03916855838234923, 0.9605224739472316)

#### 14. Create a random vector of size 30 and find the mean value (★☆☆)

In [206]:
np.random.random(30).mean()

0.5296801817645683

#### 15. Create a 2d array with 1 on the border and 0 inside (★☆☆)

In [207]:
arr = np.ones((5, 5))
arr[1:-1, 1:-1] = 0
arr

array([[1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1.]])

#### 16. How to add a border (filled with 0's) around an existing array? (★☆☆)

In [208]:
np.pad(np.ones((3, 3)), pad_width=1, mode='constant', constant_values=0)
#or
arr = np.ones((5, 5))
arr[[0, -1], :], arr[:, [0, -1]] = 0, 0
arr

array([[0., 0., 0., 0., 0.],
       [0., 1., 1., 1., 0.],
       [0., 1., 1., 1., 0.],
       [0., 1., 1., 1., 0.],
       [0., 0., 0., 0., 0.]])

#### 17. What is the result of the following expression? (★☆☆)
```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.3 == 3 * 0.1
```

In [209]:
print(0 * np.nan)
print(np.nan == np.nan)
print(np.inf > np.nan)
print(np.nan - np.nan)
print(np.nan in set([np.nan]))
print(0.3 == 3 * 0.1)

nan
False
False
nan
True
False


#### 18. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal (★☆☆)

In [210]:
np.diag(1 + np.arange(4), -1)

array([[0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0]])

#### 19. Create a 8x8 matrix and fill it with a checkerboard pattern (★☆☆)

In [211]:
arr = np.zeros((8, 8), dtype=int)
arr[::2, ::2], arr[1::2, 1::2] = 1, 1
arr

array([[1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1]])

#### 20. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element? (★☆☆)

In [212]:
np.unravel_index(99, (6, 7, 8))

(1, 5, 3)

#### 21. Create a checkerboard 8x8 matrix using the tile function (★☆☆)

In [213]:
np.tile(np.array([[0, 1], [1, 0]]), (4, 4))

array([[0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0]])

#### 22. Normalize a 5x5 random matrix (★☆☆)

In [214]:
arr = np.random.random((5, 5))
(arr - arr.mean()) / arr.std()


array([[-1.0055,  0.1769,  0.6312,  0.8273, -0.7992],
       [ 0.2527,  0.2843,  1.395 ,  1.6021,  1.1639],
       [-0.9392, -1.5345,  1.2396,  1.1404,  0.6157],
       [-1.0959, -0.2206, -1.5908, -1.2985, -0.4801],
       [-0.3771, -1.3378, -0.1465,  1.4556,  0.0411]])

#### 23. Create a custom dtype that describes a color as four unsigned bytes (RGBA) (★☆☆)

In [215]:
color = np.dtype([('r', 'ubyte'),
                  ('g', 'ubyte'),
                  ('b', 'ubyte'),
                  ('a', 'ubyte')])

#### 24. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product) (★☆☆)

In [216]:
np.dot(np.ones((5, 3)), np.ones((3, 2)))
#or
np.ones((5, 3)) @ np.ones((3, 2))

array([[3., 3.],
       [3., 3.],
       [3., 3.],
       [3., 3.],
       [3., 3.]])

#### 25. Given a 1D array, negate all elements which are between 3 and 8, in place. (★☆☆)

In [217]:
arr = np.arange(11)
arr[(3 < arr) & (arr < 8)] *= -1
arr

array([ 0,  1,  2,  3, -4, -5, -6, -7,  8,  9, 10])

#### 26. What is the output of the following script? (★☆☆)
```python
# Author: Jake VanderPlas

print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))
```

In [218]:
print(sum(range(5), -1))  #start value
print(np.sum(range(5), -1))  #dimension

9
10


#### 27. Consider an integer vector Z, which of these expressions are legal? (★☆☆)
```python
Z**Z
2 << Z >> 2
Z <- Z
1j*Z
Z/1/1
Z<Z>Z
```

In [219]:
Z = np.random.randint(10, size=(3, 3))
print(Z)
print(Z ** Z)
print(2 << Z >> 2)
print(Z < -Z)
print(1j * Z)
print(Z / 1 / 1)
# print(Z < Z > Z)

[[5 4 8]
 [3 3 8]
 [5 1 4]]
[[    3125      256 16777216]
 [      27       27 16777216]
 [    3125        1      256]]
[[ 16   8 128]
 [  4   4 128]
 [ 16   1   8]]
[[False False False]
 [False False False]
 [False False False]]
[[0.+5.j 0.+4.j 0.+8.j]
 [0.+3.j 0.+3.j 0.+8.j]
 [0.+5.j 0.+1.j 0.+4.j]]
[[5. 4. 8.]
 [3. 3. 8.]
 [5. 1. 4.]]


#### 28. What are the result of the following expressions? (★☆☆)
```python
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)
```

In [220]:
print(np.array(0) / np.array(0))
print(np.array(0) // np.array(0))
print(np.array([np.nan]).astype(int).astype(float), '\n')

print(np.array(0) % np.array(0))

nan
0
[-2.1475e+09] 

0


<ipython-input-220-491e3d9e124e>:1: RuntimeWarning: invalid value encountered in true_divide
  print(np.array(0) / np.array(0))
<ipython-input-220-491e3d9e124e>:2: RuntimeWarning: divide by zero encountered in floor_divide
  print(np.array(0) // np.array(0))
<ipython-input-220-491e3d9e124e>:5: RuntimeWarning: divide by zero encountered in remainder
  print(np.array(0) % np.array(0))


#### 29. How to round away from zero a float array ? (★☆☆)

In [221]:
arr = np.random.uniform(-10, +10, 10)
print(arr)
print(np.copysign(np.ceil(np.abs(arr)), arr))

[-8.9858e+00  8.5985e+00 -5.1447e+00  9.3919e+00 -2.8284e+00  4.2160e+00
  8.5116e+00  7.7213e-03  1.3927e+00 -3.0619e+00]
[-9.  9. -6. 10. -3.  5.  9.  1.  2. -4.]


#### 30. How to find common values between two arrays? (★☆☆)

In [222]:
np.intersect1d(np.arange(10), np.arange(5, 15))

array([5, 6, 7, 8, 9])

#### 31. How to ignore all numpy warnings (not recommended)? (★☆☆)

In [223]:
with np.errstate(all='ignore'):
    arr % 0
#or
defaults = np.seterr(all='ignore')
print(arr % 0)
np.seterr(**defaults)
print(arr % 0)

[nan nan nan nan nan nan nan nan nan nan]
[nan nan nan nan nan nan nan nan nan nan]


<ipython-input-223-bbd31a44ca3f>:7: RuntimeWarning: invalid value encountered in remainder
  print(arr % 0)


#### 32. Is the following expressions true? (★☆☆)
```python
np.sqrt(-1) == np.emath.sqrt(-1)
```

In [224]:
print(np.sqrt(-1))
print(np.emath.sqrt(-1))

nan
1j


<ipython-input-224-cefa65eb8d1f>:1: RuntimeWarning: invalid value encountered in sqrt
  print(np.sqrt(-1))


#### 33. How to get the dates of yesterday, today and tomorrow? (★☆☆)

In [225]:
np.datetime64('today') - np.timedelta64(1)
np.datetime64('today')
np.datetime64('today') + np.timedelta64(1)
#or
today = np.datetime64(datetime.today(), 'D')
delta = np.timedelta64(1, 'D')
print(today - delta)
print(today)
print(today + delta)

2021-07-26
2021-07-27
2021-07-28


#### 34. How to get all the dates corresponding to the month of July 2016? (★★☆)

In [226]:
np.arange(np.datetime64('2016-07', 'D'), np.datetime64('2016-08', 'D'), dtype="datetime64[D]")

array(['2016-07-01', '2016-07-02', '2016-07-03', '2016-07-04',
       '2016-07-05', '2016-07-06', '2016-07-07', '2016-07-08',
       '2016-07-09', '2016-07-10', '2016-07-11', '2016-07-12',
       '2016-07-13', '2016-07-14', '2016-07-15', '2016-07-16',
       '2016-07-17', '2016-07-18', '2016-07-19', '2016-07-20',
       '2016-07-21', '2016-07-22', '2016-07-23', '2016-07-24',
       '2016-07-25', '2016-07-26', '2016-07-27', '2016-07-28',
       '2016-07-29', '2016-07-30', '2016-07-31'], dtype='datetime64[D]')

#### 35. How to compute ((A+B)*(-A/2)) in place (without copy)? (★★☆)

In [227]:
A, B = npr.random((3, 3)), npr.random((3, 3))
np.add(A, B, out=B)
np.divide(A, 2, out=A)
np.negative(A, out=A)
np.multiply(A, B, out=A)

array([[-0.351 , -0.1039, -0.1605],
       [-0.3164, -0.0019, -0.1259],
       [-0.1725, -0.678 , -0.2905]])

#### 36. Extract the integer part of a random array of positive numbers using 4 different methods (★★☆)

In [228]:
arr = npr.uniform(0, 100, 10)
print(arr)
print(np.floor(arr))
print(np.trunc(arr))
print(arr.astype(int))
print(arr // 1)
print(arr - arr % 1)

[ 3.8551 71.7991 37.4889 54.6676 23.106  65.7949 79.9086 13.5886 42.6405
 87.8061]
[ 3. 71. 37. 54. 23. 65. 79. 13. 42. 87.]
[ 3. 71. 37. 54. 23. 65. 79. 13. 42. 87.]
[ 3 71 37 54 23 65 79 13 42 87]
[ 3. 71. 37. 54. 23. 65. 79. 13. 42. 87.]
[ 3. 71. 37. 54. 23. 65. 79. 13. 42. 87.]


#### 37. Create a 5x5 matrix with row values ranging from 0 to 4 (★★☆)

In [229]:
np.arange(5) * np.ones((5, 1))
#or
np.arange(5) + np.zeros((5, 5))

array([[0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.]])

#### 38. Consider a generator function that generates 10 integers and use it to build an array (★☆☆)

In [230]:
def generator():
    for x in range(10):
        yield x


np.fromiter(generator(), dtype='int32')

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

#### 39. Create a vector of size 10 with values ranging from 0 to 1, both excluded (★★☆)

In [231]:
np.linspace(0, 1, 11, endpoint=False)[1:]

array([0.0909, 0.1818, 0.2727, 0.3636, 0.4545, 0.5455, 0.6364, 0.7273,
       0.8182, 0.9091])

#### 40. Create a random vector of size 10 and sort it (★★☆)

In [232]:
np.sort(npr.random(10))

array([0.0133, 0.064 , 0.1125, 0.1663, 0.3561, 0.5707, 0.6185, 0.7465,
       0.8435, 0.9929])

#### 41. How to sum a small array faster than np.sum? (★★☆)

In [233]:
np.add.reduce(np.arange(10))

45

#### 42. Consider two random array A and B, check if they are equal (★★☆)

In [234]:
A, B = np.arange(10), np.arange(10)

np.all(A == B)
#or
np.allclose(A, B)  # Assuming identical shape of the arrays and a tolerance for the comparison of values
#or
np.array_equal(A, B)  # Checking both the shape and the element values, no tolerance (values have to be exactly equal)

True

#### 43. Make an array immutable (read-only) (★★☆)

In [235]:
arr = np.eye(3)
arr.flags.writeable = False
# arr[0, 0] = 2

#### 44. Consider a random 10x2 matrix representing cartesian coordinates, convert them to polar coordinates (★★☆)

In [236]:
arr = npr.uniform(0, 10, size=(10, 2))
Z = np.zeros((10, 2))
Z[:, 0] = np.sqrt(arr[:, 0] ** 2 + arr[:, 1] ** 2)
Z[:, 1] = np.arctan(arr[:, 1] / arr[:, 0])  #or np.arctan2(arr[:, 1], arr[:, 0])
Z

array([[12.1913,  0.6544],
       [ 9.8109,  0.9006],
       [ 7.1214,  1.0468],
       [ 8.0317,  1.498 ],
       [ 4.315 ,  0.6997],
       [10.4187,  1.2346],
       [ 9.8997,  0.4471],
       [ 9.8638,  0.3562],
       [ 5.3968,  1.0649],
       [ 6.9781,  0.1194]])

#### 45. Create random vector of size 10 and replace the maximum value by 0 (★★☆)

In [237]:
arr = npr.random(10)
arr[arr.argmax()] = 0
arr

array([0.1695, 0.1069, 0.4869, 0.7399, 0.    , 0.3468, 0.6897, 0.7019,
       0.7626, 0.7996])

#### 46. Create a structured array with `x` and `y` coordinates covering the [0,1]x[0,1] area (★★☆)

In [238]:
arr = np.zeros((5, 5), [('x', 'float64'), ('y', 'float64')])
arr['x'], arr['y'] = np.meshgrid(np.linspace(0, 1, 5), np.linspace(0, 1, 5))
arr

array([[(0.  , 0.  ), (0.25, 0.  ), (0.5 , 0.  ), (0.75, 0.  ),
        (1.  , 0.  )],
       [(0.  , 0.25), (0.25, 0.25), (0.5 , 0.25), (0.75, 0.25),
        (1.  , 0.25)],
       [(0.  , 0.5 ), (0.25, 0.5 ), (0.5 , 0.5 ), (0.75, 0.5 ),
        (1.  , 0.5 )],
       [(0.  , 0.75), (0.25, 0.75), (0.5 , 0.75), (0.75, 0.75),
        (1.  , 0.75)],
       [(0.  , 1.  ), (0.25, 1.  ), (0.5 , 1.  ), (0.75, 1.  ),
        (1.  , 1.  )]], dtype=[('x', '<f8'), ('y', '<f8')])

#### 47. Given two arrays, X and Y, construct the Cauchy matrix C (Cij =1/(xi - yj)) (★★☆)

In [239]:
X, Y = npr.random(4), npr.random(4)
np.subtract.outer(X, Y)

array([[ 0.1049,  0.1824, -0.1781,  0.3461],
       [ 0.0845,  0.1621, -0.1985,  0.3257],
       [ 0.297 ,  0.3745,  0.014 ,  0.5381],
       [ 0.1648,  0.2424, -0.1182,  0.406 ]])

#### 48. Print the minimum and maximum representable value for each numpy scalar type (★★☆)

In [240]:
print(np.iinfo('byte'))
print(np.iinfo('int32'))
print(np.iinfo('int64'), '\n')

print(np.finfo('float32'))
print(np.finfo('float64'))

Machine parameters for int8
---------------------------------------------------------------
min = -128
max = 127
---------------------------------------------------------------

Machine parameters for int32
---------------------------------------------------------------
min = -2147483648
max = 2147483647
---------------------------------------------------------------

Machine parameters for int64
---------------------------------------------------------------
min = -9223372036854775808
max = 9223372036854775807
---------------------------------------------------------------
 

Machine parameters for float32
---------------------------------------------------------------
precision =   6   resolution = 1.0000000e-06
machep =    -23   eps =        1.1920929e-07
negep =     -24   epsneg =     5.9604645e-08
minexp =   -126   tiny =       1.1754944e-38
maxexp =    128   max =        3.4028235e+38
nexp =        8   min =        -max
------------------------------------------------------------

#### 49. How to print all the values of an array? (★★☆)

In [241]:
with np.printoptions(threshold=float("inf")):
    print(np.zeros((40, 40), dtype=int))

[[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
  0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
  0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
  0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
  0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
  0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
  0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
  0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
  0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
  0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
  0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
  0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0

#### 50. How to find the closest value (to a given scalar) in a vector? (★★☆)

In [242]:
value = 34
arr = np.arange(0, 100, 10)
arr[np.abs(arr - value).argmin()]

30

#### 51. Create a structured array representing a position (x,y) and a color (r,g,b) (★★☆)

In [243]:
np.zeros(5, dtype=[
    ('position', [('x', 'f8'), ('y', 'f8')]),
    ('color', [('r', 'u1'), ('g', 'u1'), ('b', 'u1')])
])

array([((0., 0.), (0, 0, 0)), ((0., 0.), (0, 0, 0)),
       ((0., 0.), (0, 0, 0)), ((0., 0.), (0, 0, 0)),
       ((0., 0.), (0, 0, 0))],
      dtype=[('position', [('x', '<f8'), ('y', '<f8')]), ('color', [('r', 'u1'), ('g', 'u1'), ('b', 'u1')])])

#### 52. Consider a random vector with shape (100,2) representing coordinates, find point by point distances (★★☆)

In [244]:
arr = npr.random((100, 2))

np.sqrt(np.sum((arr - arr[:, np.newaxis]) ** 2, axis=2))
#or
X, Y = np.atleast_2d(arr[:, 0], arr[:, 1])
np.sqrt((X - X.T) ** 2 + (Y - Y.T) ** 2)
#or
spatial.distance.cdist(arr, arr)

array([[0.    , 0.3659, 0.3116, ..., 0.7015, 0.5974, 0.356 ],
       [0.3659, 0.    , 0.2425, ..., 0.3471, 0.2332, 0.3091],
       [0.3116, 0.2425, 0.    , ..., 0.5606, 0.3978, 0.0718],
       ...,
       [0.7015, 0.3471, 0.5606, ..., 0.    , 0.1855, 0.6122],
       [0.5974, 0.2332, 0.3978, ..., 0.1855, 0.    , 0.4407],
       [0.356 , 0.3091, 0.0718, ..., 0.6122, 0.4407, 0.    ]])

#### 53. How to convert a float (32 bits) array into an integer (32 bits) in place?

In [245]:
arr = npr.uniform(0, 100, 10).astype(np.float32)
v = arr.view(np.int32)
v[:] = arr
print(v)

[ 9 28 70 12  5 27  1 56 13  4]


#### 54. How to read the following file? (★★☆)
```
1, 2, 3, 4, 5
6,  ,  , 7, 8
 ,  , 9,10,11
```

In [246]:
s = StringIO('''1, 2, 3, 4, 5

                6,  ,  , 7, 8

                 ,  , 9,10,11
''')
Z = np.genfromtxt(s, delimiter=",", dtype=np.int)
print(Z)

[[ 1  2  3  4  5]
 [ 6 -1 -1  7  8]
 [-1 -1  9 10 11]]


#### 55. What is the equivalent of enumerate for numpy arrays? (★★☆)

In [372]:
for index, value in np.ndenumerate(np.eye(2)):
    print(index, value)
for index in np.ndindex(np.eye(2).shape):
    print(index)
for value in np.nditer(np.eye(2)):
    print(value)

(0, 0) 1.0
(0, 1) 0.0
(1, 0) 0.0
(1, 1) 1.0
(0, 0)
(0, 1)
(1, 0)
(1, 1)
1.0
0.0
0.0
1.0


#### 56. Generate a generic 2D Gaussian-like array (★★☆)

In [247]:
#TODO

#### 57. How to randomly place p elements in a 2D array? (★★☆)

In [292]:
n = 5
p = 3
Z = np.zeros((n, n))
Z.put(np.random.choice(range(n * n), p, replace=False), 1)
print(Z)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 0. 1. 1.]]


array([21,  9, 23])

#### 58. Subtract the mean of each row of a matrix (★★☆)

In [295]:
arr = np.arange(9).reshape(3, 3)

arr - np.mean(arr, axis=1)[:, np.newaxis]
#or
arr - np.mean(arr, axis=1, keepdims=True)

array([[-1.,  0.,  1.],
       [-1.,  0.,  1.],
       [-1.,  0.,  1.]])

#### 59. How to sort an array by the nth column? (★★☆)

In [250]:
arr = npr.randint(0, 10, (5, 5))
print(arr)
arr = arr[np.argsort(arr[:, 2])]
arr

[[5 0 2 7 4]
 [6 3 3 9 2]
 [2 7 3 1 5]
 [6 5 1 1 5]
 [4 9 9 3 6]]


array([[6, 5, 1, 1, 5],
       [5, 0, 2, 7, 4],
       [6, 3, 3, 9, 2],
       [2, 7, 3, 1, 5],
       [4, 9, 9, 3, 6]])

#### 60. How to tell if a given 2D array has null columns? (★★☆)

In [354]:
Z = np.random.randint(0, 3, (3, 10))
print(Z)
(Z == 0).all(axis=0).any()
#or
(~Z.any(axis=0)).any()

[[0 1 1 0 0 2 2 1 0 0]
 [1 1 2 2 2 1 1 0 0 1]
 [1 0 1 0 2 2 0 1 1 1]]


False

#### 61. Find the nearest value from a given value in an array (★★☆)

In [364]:
val = 50
arr = npr.choice(range(100), size=(3, 3), replace=False)
print(arr)
print(np.abs(arr - val))
np.unravel_index(np.abs(arr - val).argmin(), arr.shape)

[[ 0 29 16]
 [75 81 50]
 [76 24 13]]
[[50 21 34]
 [25 31  0]
 [26 26 37]]


(1, 2)

#### 62. Considering two arrays with shape (1,3) and (3,1), how to compute their sum using an iterator? (★★☆)

In [450]:

A = np.arange(3).reshape(1, 3)
B = np.arange(3).reshape(3, 1)
it = np.nditer([A, B, None])
for x, y, z in it:
    z[...] = x + y
it.operands[2]

array([[16843008,    65793, 16843009],
       [16777473, 16843009, 16842753],
       [16843009, 16843008,    65793]])

#### 63. Create an array class that has a name attribute (★★☆)

In [377]:
#TODO

#### 64. Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)? (★★★)

In [404]:
vec1 = np.arange(10)
vec2 = npr.choice(10, 10)
np.add.at(vec1, vec2, 1)
vec1

array([ 1,  2,  3,  5,  4,  5,  8,  8,  9, 10])

#### 65. How to accumulate elements of a vector (X) to an array (F) based on an index list (I)? (★★★)

In [456]:
#TODO
# X = np.arange(10)
# I = npr.choice(10, 10)
# print(X)
# print(I)
# print(np.bincount(I, X))
# #or
# np.multiply.accumulate(X[I])

[0 1 2 3 4 5 6 7 8 9]
[4 1 9 4 5 6 0 4 7 5]
[ 6.  1.  0.  0. 10. 13.  5.  8.  0.  2.]


array([   4,    4,   36,  144,  720, 4320,    0,    0,    0,    0],
      dtype=int32)

#### 66. Considering a (w,h,3) image of (dtype=ubyte), compute the number of unique colors (★★☆)

In [431]:
#TODO
# len(np.unique(npr.choice(10, 10)))

6

#### 67. Considering a four dimensions array, how to get sum over the last two axis at once? (★★★)

#### 68. Considering a one-dimensional vector D, how to compute means of subsets of D using a vector S of same size describing subset  indices? (★★★)

#### 69. How to get the diagonal of a dot product? (★★★)

#### 70. Consider the vector [1, 2, 3, 4, 5], how to build a new vector with 3 consecutive zeros interleaved between each value? (★★★)

#### 71. Consider an array of dimension (5,5,3), how to mulitply it by an array with dimensions (5,5)? (★★★)

#### 72. How to swap two rows of an array? (★★★)

#### 73. Consider a set of 10 triplets describing 10 triangles (with shared vertices), find the set of unique line segments composing all the  triangles (★★★)

#### 74. Given a sorted array C that corresponds to a bincount, how to produce an array A such that np.bincount(A) == C? (★★★)

#### 75. How to compute averages using a sliding window over an array? (★★★)

#### 76. Consider a one-dimensional array Z, build a two-dimensional array whose first row is (Z[0],Z[1],Z[2]) and each subsequent row is  shifted by 1 (last row should be (Z[-3],Z[-2],Z[-1]) (★★★)

#### 77. How to negate a boolean, or to change the sign of a float inplace? (★★★)

#### 78. Consider 2 sets of points P0,P1 describing lines (2d) and a point p, how to compute distance from p to each line i (P0[i],P1[i])? (★★★)

#### 79. Consider 2 sets of points P0,P1 describing lines (2d) and a set of points P, how to compute distance from each point j (P[j]) to each line i (P0[i],P1[i])? (★★★)

#### 80. Consider an arbitrary array, write a function that extract a subpart with a fixed shape and centered on a given element (pad with a `fill` value when necessary) (★★★)

#### 81. Consider an array Z = [1,2,3,4,5,6,7,8,9,10,11,12,13,14], how to generate an array R = [[1,2,3,4], [2,3,4,5], [3,4,5,6], ..., [11,12,13,14]]? (★★★)

#### 82. Compute a matrix rank (★★★)

#### 83. How to find the most frequent value in an array?

#### 84. Extract all the contiguous 3x3 blocks from a random 10x10 matrix (★★★)

#### 85. Create a 2D array subclass such that Z[i,j] == Z[j,i] (★★★)

#### 86. Consider a set of p matrices wich shape (n,n) and a set of p vectors with shape (n,1). How to compute the sum of of the p matrix products at once? (result has shape (n,1)) (★★★)

#### 87. Consider a 16x16 array, how to get the block-sum (block size is 4x4)? (★★★)

#### 88. How to implement the Game of Life using numpy arrays? (★★★)

#### 89. How to get the n largest values of an array (★★★)

#### 90. Given an arbitrary number of vectors, build the cartesian product (every combinations of every item) (★★★)

#### 91. How to create a record array from a regular array? (★★★)

#### 92. Consider a large vector Z, compute Z to the power of 3 using 3 different methods (★★★)

#### 93. Consider two arrays A and B of shape (8,3) and (2,2). How to find rows of A that contain elements of each row of B regardless of the order of the elements in B? (★★★)

#### 94. Considering a 10x3 matrix, extract rows with unequal values (e.g. [2,2,3]) (★★★)

#### 95. Convert a vector of ints into a matrix binary representation (★★★)

#### 96. Given a two dimensional array, how to extract unique rows? (★★★)

#### 97. Considering 2 vectors A & B, write the einsum equivalent of inner, outer, sum, and mul function (★★★)

#### 98. Considering a path described by two vectors (X,Y), how to sample it using equidistant samples (★★★)?

#### 99. Given an integer n and a 2D array X, select from X the rows which can be interpreted as draws from a multinomial distribution with n degrees, i.e., the rows which only contain integers and which sum to n. (★★★)

#### 100. Compute bootstrapped 95% confidence intervals for the mean of a 1D array X (i.e., resample the elements of an array with replacement N times, compute the mean of each sample, and then compute percentiles over the means). (★★★)