In [1]:
import numpy as np
from numpy import linalg
from scipy import special
from numba import vectorize

np.__version__

'1.19.5'

### 1 CREATING

In [2]:
def generator():
    for x in range(10):
        yield x


arr = np.array([[1, 2, 3], [-3, -2, -1]], dtype='int32')
print(arr)
print(np.array([
    [j if j % 2 == 0 else 0 for j in range(i, i + 3)]
    for i in range(2, 5)]), '\n')

print(np.zeros((2, 5)))
print(np.ones((2, 2, 3), dtype=int))
print(np.full(arr.shape, round(np.pi, 3)))
print(np.full_like(arr, round(np.e, 3)), '\n')

print(np.arange(0, 20, 2))
print(np.linspace(0, 1, 5), '\n')

print(np.random.random((3, 3)))
print(np.random.uniform(1, 2, (3, 3)))
print(np.random.normal(0, 1, (2, 2)), '\n')

print(np.eye(4, dtype='int'))
print(np.diag(1 + np.arange(3), 1))
print(np.tril(np.ones((3, 3)), -1))
print(np.empty(2))

[[ 1  2  3]
 [-3 -2 -1]]
[[2 0 4]
 [0 4 0]
 [4 0 6]] 

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
[[[1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]]]
[[3.142 3.142 3.142]
 [3.142 3.142 3.142]]
[[2 2 2]
 [2 2 2]] 

[ 0  2  4  6  8 10 12 14 16 18]
[0.   0.25 0.5  0.75 1.  ] 

[[0.04480115 0.65282645 0.40785828]
 [0.9462745  0.13279199 0.70492652]
 [0.85179335 0.80360576 0.37856619]]
[[1.48033687 1.76039623 1.82757341]
 [1.8686464  1.44845512 1.14679546]
 [1.69053687 1.29941347 1.94706522]]
[[-0.18612212 -1.29067034]
 [ 1.73706109 -1.42468537]] 

[[1 0 0 0]
 [0 1 0 0]
 [0 0 1 0]
 [0 0 0 1]]
[[0 1 0 0]
 [0 0 2 0]
 [0 0 0 3]
 [0 0 0 0]]
[[0. 0. 0.]
 [1. 0. 0.]
 [1. 1. 0.]]
[0. 1.]


### 2 ATRIBUTES

In [3]:
np.set_printoptions(precision=4)

x3 = np.random.randint(10, size=(2, 3, 4))
print(x3.ndim)
print(x3.size)
print(x3.shape, "\n")

print(x3.dtype)
print(x3.itemsize)
print(x3.nbytes)
print(x3.flags, '\n')

print(np.issubdtype(x3.dtype, np.floating))
print(np.issubdtype(x3.dtype, np.number))
print(arr.astype('float64'))
print(np.float64(arr))

3
24
(2, 3, 4) 

int32
4
96
  C_CONTIGUOUS : True
  F_CONTIGUOUS : False
  OWNDATA : True
  WRITEABLE : True
  ALIGNED : True
  WRITEBACKIFCOPY : False
  UPDATEIFCOPY : False
 

False
True
[[ 1.  2.  3.]
 [-3. -2. -1.]]
[[ 1.  2.  3.]
 [-3. -2. -1.]]


### 3 INDEXING

In [4]:
print(x3)
print(x3[1][2][3])
print(x3[1, 2, 3])
x3[1, 2, -3] = 7
print(x3[1, 2, -3])
print(x3[-1])
print(x3[..., 1]) # all remained dimensions
print(np.unravel_index(20, x3.shape))

[[[4 4 2 5]
  [5 9 6 1]
  [0 8 0 9]]

 [[2 9 3 2]
  [4 0 5 5]
  [0 0 8 5]]]
5
5
7
[[2 9 3 2]
 [4 0 5 5]
 [0 7 8 5]]
[[4 9 8]
 [9 0 7]]
(1, 2, 0)


### 4 SLICING

In [5]:
r = np.arange(10)
print(r[:5])
print(r[::3])
print(r[3::2], '\n')

print(r[::-1])
print(r[2::-2])
print(r[-2::-2], '=====\n')

print(x3[:, 1:, :-1], '\n')
print(x3[:1, ::2, ::-1], '\n')
print(x3[1][1][:], '=====\n')

sr = r[:5]  #refers to the same data
cr = r[:5].copy('C')  #by row ('C'/'F' for efficiency increase)
sr[2:4] = [228, 228]
cr[3] = 322
print(r)

[0 1 2 3 4]
[0 3 6 9]
[3 5 7 9] 

[9 8 7 6 5 4 3 2 1 0]
[2 0]
[8 6 4 2 0] =====

[[[5 9 6]
  [0 8 0]]

 [[4 0 5]
  [0 7 8]]] 

[[[5 2 4 4]
  [9 0 8 0]]] 

[4 0 5 5] =====

[  0   1 228 228   4   5   6   7   8   9]


### 5 RESHAPING

In [6]:
print(x3.reshape(1, 2, 12))
print(np.arange(12).reshape(-1, 6))  #type inference
print(x3.ravel())  #same data
print(x3.flatten())  #copy of data
print(x3.ravel('F'), '\n')  #pass by column

print(r[:, np.newaxis])
print(arr.T)
print(x3.transpose(1, 0, 2))
print(x3.swapaxes(1, 2))

[[[4 4 2 5 5 9 6 1 0 8 0 9]
  [2 9 3 2 4 0 5 5 0 7 8 5]]]
[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]]
[4 4 2 5 5 9 6 1 0 8 0 9 2 9 3 2 4 0 5 5 0 7 8 5]
[4 4 2 5 5 9 6 1 0 8 0 9 2 9 3 2 4 0 5 5 0 7 8 5]
[4 2 5 4 0 0 4 9 9 0 8 7 2 3 6 5 0 8 5 2 1 5 9 5] 

[[  0]
 [  1]
 [228]
 [228]
 [  4]
 [  5]
 [  6]
 [  7]
 [  8]
 [  9]]
[[ 1 -3]
 [ 2 -2]
 [ 3 -1]]
[[[4 4 2 5]
  [2 9 3 2]]

 [[5 9 6 1]
  [4 0 5 5]]

 [[0 8 0 9]
  [0 7 8 5]]]
[[[4 5 0]
  [4 9 8]
  [2 6 0]
  [5 1 9]]

 [[2 4 0]
  [9 0 7]
  [3 5 8]
  [2 5 5]]]


### 6 MERGING

In [7]:
x = np.array([2, 3, 4])
y = np.array([4, 5, 6])
print(np.concatenate([x, y]))
print(np.hstack([x, y]))
print(np.r_[x, y])
print(np.concatenate([[x], [y]], axis=0))
print(np.vstack([x, y]))
print(np.c_[x, y], '\n')

print(arr.repeat(3))
print(arr.repeat(3, axis=1))
print(np.tile(arr, 3))
print(np.tile(arr, (2, 1)), '\n')

X, Y = np.meshgrid(x, y)
print(X)
print(Y)

[2 3 4 4 5 6]
[2 3 4 4 5 6]
[2 3 4 4 5 6]
[[2 3 4]
 [4 5 6]]
[[2 3 4]
 [4 5 6]]
[[2 4]
 [3 5]
 [4 6]] 

[ 1  1  1  2  2  2  3  3  3 -3 -3 -3 -2 -2 -2 -1 -1 -1]
[[ 1  1  1  2  2  2  3  3  3]
 [-3 -3 -3 -2 -2 -2 -1 -1 -1]]
[[ 1  2  3  1  2  3  1  2  3]
 [-3 -2 -1 -3 -2 -1 -3 -2 -1]]
[[ 1  2  3]
 [-3 -2 -1]
 [ 1  2  3]
 [-3 -2 -1]] 

[[2 3 4]
 [2 3 4]
 [2 3 4]]
[[4 4 4]
 [5 5 5]
 [6 6 6]]


### 7 PARTITION

In [8]:
r1, r2, r3 = np.split(r, [3, 7])
print(r1, r2, r3)
e1, e2 = np.hsplit(np.eye(4, dtype='int64'), [2])
print(e1)
print(e2)
e1, e2 = np.vsplit(np.eye(4, dtype='int64'), [2])
print(e1)
print(e2)

[  0   1 228] [228   4   5   6] [7 8 9]
[[1 0]
 [0 1]
 [0 0]
 [0 0]]
[[0 0]
 [0 0]
 [1 0]
 [0 1]]
[[1 0 0 0]
 [0 1 0 0]]
[[0 0 1 0]
 [0 0 0 1]]


### 8 UNIVERSAL FUNCTIONTS: CALCULATING (more efficiently)

In [9]:
@vectorize  #effective
def custom_add(x, y):
    return x + y * 10


print(arr / 2)
print(2 ** arr.astype('float64'))
print(custom_add(x, 2), '\n')  #sum

print(np.sign(np.array([-5, 5])))
print(np.abs(np.array([-5, 5])))
print(np.emath.sqrt(np.arange(0, -10, -1)))  #consider imaginary values
print(np.sin(x))
print(np.exp2(x))
print(np.log2(x))
print(np.log1p(x))  #more precisely
print(special.gamma(x))
print(special.erfc(x), '\n')

np.multiply(x, 10, out=r[7:10])  #modifying without copying
print(r)
print(np.add.reduce(x))  #sum (faster than np.sum())
print(np.add.reduceat(r, [0, 2, 5]))  #interval sum
print(np.multiply.accumulate(x))  #cumprod
print(np.power.outer(x, x))  # for each pair

[[ 0.5  1.   1.5]
 [-1.5 -1.  -0.5]]
[[2.    4.    8.   ]
 [0.125 0.25  0.5  ]]
[22 23 24] 

[-1  1]
[5 5]
[0.+0.j     0.+1.j     0.+1.4142j 0.+1.7321j 0.+2.j     0.+2.2361j
 0.+2.4495j 0.+2.6458j 0.+2.8284j 0.+3.j    ]
[ 0.9093  0.1411 -0.7568]
[ 4.  8. 16.]
[1.    1.585 2.   ]
[1.0986 1.3863 1.6094]
[1. 2. 6.]
[4.6777e-03 2.2090e-05 1.5417e-08] 

[  0   1 228 228   4   5   6  20  30  40]
9
[  1 460 101]
[ 2  6 24]
[[  4   8  16]
 [  9  27  81]
 [ 16  64 256]]


### 9 AGGREGATING (effective)

In [10]:
print(np.sum(x))
print(np.cumsum(x))
print(x3.argmax(axis=2))
print(np.std(x))
print(x3.mean(0).mean(0))  #concerning axis

9
[2 5 9]
[[3 1 3]
 [1 2 2]]
0.816496580927726
[2.5    6.1667 4.     4.5   ]


### 10 TRANSLATION (HARD) (or stacking)

In [11]:
y = y.ravel()[:, np.newaxis]
print(np.ones((3, 3)) + 3)
print(np.ones((3, 3)) * x)
print(np.logaddexp(x, y))
e1[:] = np.arange(4)
print(e1, '\n')

xy = x * y
print(xy - xy.mean(0))  #centering
print(np.sin(x) ** 10 + np.cos(10 + y * x) * np.cos(x))  #two-dimensional function

[[4. 4. 4.]
 [4. 4. 4.]
 [4. 4. 4.]]
[[2. 3. 4.]
 [2. 3. 4.]
 [2. 3. 4.]]
[[4.1269 4.3133 4.6931]
 [5.0486 5.1269 5.3133]
 [6.0181 6.0486 6.1269]]
[[0 1 2 3]
 [0 1 2 3]] 

[[-2. -3. -4.]
 [ 0.  0.  0.]
 [ 2.  3.  4.]]
[[ 0.1116  0.99   -0.3612]
 [ 0.2166 -0.9813 -0.0392]
 [ 0.8026  0.953   0.6163]]


### 11 UF: COMPARISON (effective)

In [12]:
print(np.greater(xy, 12))
print(xy < 18)
print(np.where(xy < 18, '<18', '>=18'))
mask = (xy > 12) & (xy < 18)
print(mask)
print(xy[mask])
print(np.all(xy > 5))
print(np.nonzero(np.eye(2)))
print(np.count_nonzero(xy > 12))

[[False False  True]
 [False  True  True]
 [False  True  True]]
[[ True  True  True]
 [ True  True False]
 [ True False False]]
[['<18' '<18' '<18']
 ['<18' '<18' '>=18']
 ['<18' '>=18' '>=18']]
[[False False  True]
 [False  True False]
 [False False False]]
[16 15]
True
(array([0, 1], dtype=int64), array([0, 1], dtype=int64))
5


### 12 FANCY INDEXING (copies data everytime) (HARD)

In [13]:
print(r[[3, 5, 7]])  # -> numbers
print(r[np.array([[0, 1], [1, 2]])], '\n')  # -> array

print(xy[:, [0, 1]])  # -> rows/cols
print(xy.take([0, 2], axis=1))  # -> rows/cols
print(xy[[0, 1], [1, 2]])  # -> numbers

print(xy[[0, 1]][:, [1, 2]])  # -> array
print(xy[np.array([[0, 1], [1, 2]]), np.array([[0, 1], [1, 2]])])  # -> array (kill me please)
print(xy[np.array([0, 1])[:, np.newaxis], [1, 2]], '\n')  # -> array (index translation (kill me please X2))
print(xy[np.array([1, 1, 2])[:, np.newaxis], np.array([True, False, True])], '\n')  #using mask

ind = [0, 5, 9]
r[ind] = 99  #same
r.put(ind, 99)  #same
print(r)
r[ind] *= 2
print(r)
np.add.at(r, ind, 2)  # applies operation to elements at indices
print(r)

[228   5  20]
[[  0   1]
 [  1 228]] 

[[ 8 12]
 [10 15]
 [12 18]]
[[ 8 16]
 [10 20]
 [12 24]]
[12 20]
[[12 16]
 [15 20]]
[[ 8 15]
 [15 24]]
[[12 16]
 [15 20]] 

[[10 20]
 [10 20]
 [12 24]] 

[ 99   1 228 228   4  99   6  20  30  99]
[198   1 228 228   4 198   6  20  30 198]
[200   1 228 228   4 200   6  20  30 200]


### 13 SORTING

In [14]:
print(np.sort(r))  #copy
print(np.argsort(r, kind='mergesort'))  #sustainable
x3[0].sort(axis=1)  #modifies source
print(x3[0])
print(np.partition(r, 3))
print(np.argpartition(r, 3))
print(np.arange(0, 25, 5).searchsorted([10, 20, 30]))

[  1   4   6  20  30 200 200 200 228 228]
[1 4 6 7 8 0 5 9 2 3]
[[2 4 4 5]
 [1 5 6 9]
 [0 0 8 9]]
[  4   1   6  20  30 200 200 228 228 200]
[4 1 6 7 8 0 5 3 2 9]
[2 4 5]


### 14 STRUCTURES

In [15]:
#initialization
data = np.zeros(3, dtype={'names': ('name', 'age'), 'formats': ('<U10', '>i4')})
data = np.zeros(3, 'U10,i4')
data = np.zeros(3, [('name', 'U10'), ('age', 'i4')])
data2 = np.zeros(3, dtype=np.dtype([('id', 'i8'), ('mat', 'f8', (3, 3))]))
data3 = np.zeros(3, dtype=np.dtype([('id', 'i8'), ('list', [('a', 'f8'), ('b', 'f4')])]))
print(data.dtype)
print(data.dtype.names)
print(data2.dtype)
print(data3.dtype, '\n')

#access
data['name'] = ['Nice', 'Dick', 'Bro']
data['age'][2] = 5
print(data['age'])
print(data['name'][0])
print(data[data['age'] > 2]['name'])
print(data2[0]['mat'][0])
print(data3['list']['a'])

[('name', '<U10'), ('age', '<i4')]
('name', 'age')
[('id', '<i8'), ('mat', '<f8', (3, 3))]
[('id', '<i8'), ('list', [('a', '<f8'), ('b', '<f4')])] 

[0 0 5]
Nice
['Bro']
[0. 0. 0.]
[0. 0. 0.]


### 15 DATETIME64

In [16]:
date = np.datetime64('2015-07-30')
np.datetime64('2015-07-30T20:45', 'ns')
date + np.arange(4)

array(['2015-07-30', '2015-07-31', '2015-08-01', '2015-08-02'],
      dtype='datetime64[D]')

### 16 SET OPERATIONS

In [17]:
print(np.unique(r))
print(np.in1d(r, x))  #presence
print(np.intersect1d(r, x))

[  1   4   6  20  30 200 228]
[False False False False  True False False False False False]
[4]


### 17 FILES

In [18]:
np.save('out/xy_arr.npy', xy)
np.savez('out/xy_arr.npz', a=x, b=y)  #zip
np.savez_compressed('out/xy_arr_comp.npz', a=x, b=y)  #compressed zip
xy_z = np.load('out/xy_arr.npz')
print(xy_z['a'], '\n')

mmap = np.memmap(filename='out/map1000', dtype='int32', shape=(100, 100))
section = mmap[-2:, -2:]  #representation
section[:] = 12
mmap.flush()  #save changes
print(mmap)
del mmap

[2 3 4] 

[[ 0  0  0 ...  0  0  0]
 [ 0  0  0 ...  0  0  0]
 [ 0  0  0 ...  0  0  0]
 ...
 [ 0  0  0 ... 12 12 12]
 [ 0  0  0 ... 12 12 12]
 [ 0  0  0 ... 12 12 12]]


### 18 LINEAR ALGEBRA

In [19]:
print(np.dot(arr, arr.T))  #matrix product
print(arr @ arr.T)  #also
print(linalg.inv(np.arange(4).reshape(2, 2)))
print(linalg.solve(a=np.arange(4).reshape(2, 2), b=[5, 7]))
print(linalg.det(xy))

[[ 14 -10]
 [-10  14]]
[[ 14 -10]
 [-10  14]]
[[-1.5  0.5]
 [ 1.   0. ]]
[-4.  5.]
0.0
